-- Create Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  description text,
  type text default 'info', -- 'info', 'warning', 'success', 'error'
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.notifications enable row level security;

-- Policies
create policy "Users can view their own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);

create policy "Admins can insert notifications"
  on public.notifications for insert
  with check (true); -- ideally restrict to admin role, but keeping open for now for simulation

create policy "Users can update their own notifications (mark as read)"
  on public.notifications for update
  using (auth.uid() = user_id);

-- Insert sample notification for current users (optional, manual run)
-- insert into notifications (user_id, title, description, type) values (..., 'Welcome', 'Welcome to SmartAttend', 'info');
